### ISSUE TITLE
Should People Page Link to Uprizer?

### ISSUE THREAD

**Issue by Ademan** [freenet/website#15]
[The about page](https://github.com/freenet/website/blob/c898c26cc39799abeffa1429c50e940fbbc7ad0b/pages/about.py#L261) links to http://www.sensearray.com/ for Ian, but that URL appears defunct. Should we link to http://uprizer.com/ instead?

**Comment by Thynix** [comment]
Yeah, that's probably a good idea. It should be up to Ian though. Have you asked Ian?

**Comment by sanity** [comment]
Hey guys, sorry for the slow response.

The best thing to link to for me is my personal blog at http://blog.locut.us/ - please let me know if you have any questions.

**Comment by sanity** [comment]
perhaps replace:

> In his day job, Ian is the founder and CEO of \[SenseArray\](http://sensearray.com/).

With:

> Learn more about Ian on his \[personal website\](http://blog.locut.us/)

**Comment by Thynix** [comment]
Sure, will do.
