### ISSUE TITLE
generate script breaks Markdown code blocks

### ISSUE THREAD

**Issue by bertm** [freenet/website#4]
The regular expression in the method `install_clean_gettext` in `generate`, intended to make text more readable for translators, breaks Markdown codeblock syntax. This is clearly visible in the output of the documentation page, where content intended as code blocks is formatted as normal paragraph.

Example input that breaks:

```
A typical CHK key looks like this:

    CHK@file hash,decryption key,crypto settings

or for example:

    CHK@SVbD9~HM5nzf3AX4yFCBc-A4dhNUF5DPJZLL5NX5Brs,bA7qLNJR7IXRKn6uS5PAySjIM6azPFvK~18kSi6bbNQ,AAEA--8

The decryption key is stored encrypted within the file, so it is not possible
to decrypt the file without the CHK key.
```

This is converted to:

```
A typical CHK key looks like this:

CHK@file hash,decryption key,crypto settings

or for example:

CHK@SVbD9~HM5nzf3AX4yFCBc-A4dhNUF5DPJZLL5NX5Brs,bA7qLNJR7IXRKn6uS5PAySjIM6azPFvK~18kSi6bbNQ,AAEA--8

The decryption key is stored encrypted within the file, so it is not possible
to decrypt the file without the CHK key.
```

The regular expression deletes the preceding whitespace on all lines, which is actually meaningful in this context. Changing

``` python
search = re.sub(r"^[ \t]+", "", text.strip(), flags=re.MULTILINE)
```

to

``` python
search = re.sub(r"^[ \t]+$", "", text.strip(), flags=re.MULTILINE)
```

seems to fix at least this occurence – however I'm not confident that this does not break the intended functionality of this method, since I don't really understand what it's _supposed_ to do.

**Comment by Thynix** [comment]
My understanding is it's intended to allow text blocks to be indented in multiline strings without that whitespace appearing in the version to be localized. I think I'd rather that all the strings are not indented and remove the regex entirely.

The new expression removes all lines consisting only of whitespace - are there any instances of it?

**Comment by bertm** [comment]
I agree that we should drop the regex and actually fix the problems that the regex tries to solve.

**Comment by Thynix** [comment]
Once we fix this we'll be able to close the GitHub issue tracker in favor of the project bug tracker.

**Comment by nextgens** [comment]
This doesn't apply to the current website.
