### ISSUE TITLE
Untranslated strings in main page

### ISSUE THREAD

**Issue by desyncr** [freenet/website#75]
[Here](http://i.imgur.com/4QR93n0.jpg) is a screenshot. It appears untranslated in any language.

**Comment by Thynix** [comment]
The Spanish translation is complete but not yet deployed; I'll deploy it
this weekend.

**Comment by desyncr** [comment]
Alright. Take into account that it is not only happening in Spanish, but in all translations.

**Comment by Thynix** [comment]
Understood. I've deployed Spanish and French translation updates, which are the only translations which have been updated.

**Comment by desyncr** [comment]
Now it looks fine in Spanish and French. Thanks :+1:
