### ISSUE TITLE
Add MantisHub to list of Sponsors

### ISSUE THREAD

**Issue by Ademan-laptop** [freenet/website#83]
xor mentioned that we should add MantisHub to our sponsor list, thoughts?

**Comment by Ademan-laptop** [comment]
+1

**Comment by Thynix** [comment]
Sure, that makes sense to me. We should also at some point add a news entry and tweet about it.

**Comment by Thynix** [comment]
Resolved by 53e7b44d92d7aa3ab3222b3b9e3aaa99da7b86b6.
